version: "2.2"

services:
  es01:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
      xpack.security.enabled: false
      elasticsearch.ssl.verificationMode: "none"

volumes:
  esdata01:
    driver: local
  kibanadata:
    driver: local